# This workflow will be triggered manually to deploy code in Heroku

name: Deploy Code to Heroku
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Environment'
        type: choice
        required: true
        default: 'staging'
        options:
          - production
          - staging
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch all tags
        run: git fetch --tags

      - name: Determine branch or tag
        id: ref_type
        run: |
          if [[ ${{ github.ref }} == refs/heads/* ]]; then
            echo "BRANCH"
            echo "::set-output name=ref_flag::branch"
          fi

      - name: Use branch/tag data
        run: |
          ref_flag=${{ steps.ref_check.outputs.ref_flag }}
          echo "Ref is a $ref_flag"
        
      - name: "Deploy to ${{ github.event.inputs.environment }}"
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key:  ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ github.event.inputs.environment == 'production' && secrets.HEROKU_PRODUCTION_APP_NAME || secrets.HEROKU_STAGING_APP_NAME }}
          heroku_email: 'narendra.gaindhar@idrive.com'
          branch: ${{ ! startsWith(github.ref, 'refs/tags/') && github.ref || 'master' }}

      - name: Slack Notification
        if: always()
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "text": "Deployment Status: ${{ job.status }}\nDeploy by: ${{ github.actor }}\nDeploy to: ${{ github.event.inputs.environment}}"
            }
