# This workflow will be triggered manually to deploy code in Heroku

name: Deploy Code to Heroku
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Environment'
        type: choice
        required: true
        default: 'staging'
        options:
          - production
          - staging
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch all tags
        run: git fetch --tags

      - name: Set up Git
        run: |
          git config user.email "naren.gaindhar95@gmail.com"
          git config user.name "narendragaindhar"

      - name: Update Version File and Create Tag
        run: |
          if [ -n "${{ github.ref_type == 'tag' && github.ref  }}" ]; then
            tag=$(echo "${{ github.ref }}" | sed 's|refs/tags/||')
            echo "Updating version file with tag: $tag"
            echo "$tag" > config/version
            git add config/version
            git commit -m "Bumping version to: $tag"
          else
            echo "No tag specified. Skipping version file update."
          fi

      - name: Push latest version to tag
        if: github.ref_type == 'tag' && github.ref
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          branch: github.ref
