# This workflow will be triggered manually to deploy code in Heroku

name: Deploy Code to Heroku
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Environment'
        type: choice
        required: true
        default: 'staging'
        options:
          - production
          - staging
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch all tags
        run: git fetch --tags

      - name: Determine branch or tag
        id: ref_type
        run: |
          if [[ ${{ github.ref }} == refs/heads/* ]]; then
            echo "BRANCH"
          else 
            echo "TAG"
          fi
        
      - name: "Deploy to ${{ github.event.inputs.environment }}"
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key:  ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ github.event.inputs.environment == 'production' && secrets.HEROKU_PRODUCTION_APP_NAME || secrets.HEROKU_STAGING_APP_NAME }}
          heroku_email: 'narendra.gaindhar@idrive.com'
          branch: ${{ github.ref == refs/heads/* && 'master' || github.ref }}
          #branch: ${{ ! startsWith(github.ref, 'refs/tags/') && github.ref || 'master' }}
