# This workflow will be triggered manually to deploy code in Heroku

name: Deploy Code to Heroku
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Environment'
        type: choice
        required: true
        default: 'staging'
        options:
          - production
          - staging
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
           token: ${{ secrets.TOKEN_GITHUB }}

      - name: Fetch all tags
        run: git fetch --tags

      - name: Set up Git
        run: |
          git config user.email "naren.gaindhar95@gmail.com"
          git config user.name "narendragaindhar"

      - name: Update Version File and Create Tag
        run: |
          if [ -n "${{ github.ref_type == 'tag' && github.ref  }}" ]; then
            tag=$(echo "${{ github.ref }}" | sed 's|refs/tags/||')
            echo "Updating version file with tag: $tag"
            echo "$tag" > config/version
            git add config/version
            git tag -a -f $tag  -m "Bumping version to: $tag"
            git push -f origin $tag
          else
            echo "No tag specified. Skipping version file update."
          fi
