name: Release Tag Workflow

on:
  workflow_dispatch:
    inputs:
      tag_type:
        description: 'Tag Type'
        required: true
        default: 'minor'
        type: choice
        options:
          - 'major'
          - 'minor'
          - 'patch'

jobs:
  release:
    runs-on: ubuntu-22.04
    
    env:
      IBACKUP_UPDATE_API_TOKEN: 'xxxx'
      IBACKUP_UPDATE_URL: 'xxxx'
      IDRIVE_UPDATE_API_TOKEN: 'xxx'
      IDRIVE_UPDATE_URL: 'xxxx'
      IDRIVE360_UPDATE_API_TOKEN: 'xxxx'
      IDRIVE360_UPDATE_URL: 'xxxx'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
           token: ${{ secrets.TOKEN_GITHUB }}
  
      - name: Set up Git
        run: |
          git config user.email "${{ secrets.USER_EMAIL }}"
          git config user.name "${{ secrets.USER_NAME }}"

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Run Rake Release Task
        run: |
          if [[ "${{ github.event.inputs.tag_type }}" == "major" ]]; then
            bundle exec rake release:major
          elif [[ "${{ github.event.inputs.tag_type }}" == "minor" ]]; then
            bundle exec rake release:minor
          elif [[ "${{ github.event.inputs.tag_type }}" == "patch" ]]; then
            bundle exec rake release:patch
          fi
